name: Sochat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  animated_text_kit: ^3.1.2
  cupertino_icons: ^1.0.0
  custom_navigation_bar: ^0.7.1
  eva_icons_flutter: ^2.0.1
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  font_awesome_flutter: ^8.11.0
  google_sign_in: ^4.5.9
  image_picker: ^0.6.7+22
  lottie: ^0.7.0+1
  flutter_signin_button: ^1.1.0
 
  page_transition: ^1.1.7+6
  provider: ^4.3.3
  timeago: ^2.0.30

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/login.png
    - assets/images/empty.png
    - assets/icons/sunflower.png
    - assets/animations/loading.json
    - assets/animations/loadingimage.json
    - assets/animations/dotloading.json
    - assets/animations/emptypicture.json
    - assets/animations/addposts.json
    

    
    - assets/animations/splashscreen.json
    - assets/animations/astronaut.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
    - family: Monteserrat
      fonts:
        - asset: assets/fonts/Monteserat.ttf
